### ISSUE TITLE
Is this needed?

### ISSUE THREAD

**Issue by FISHMANPET** [umn-microsoft-automation/UMN-Google#32]
https://github.com/umn-microsoft-automation/UMN-Google/blob/93e0669e7696ffa33bde1871123b9a939aeee6ed/UMN-Google.psm1#L176

Is $projectID needed for this?  I can't see it but maybe I'm missing something?

**Comment by travis-sobeck** [comment]
@kylecweeks I don't see it being used anywhere and I'm not sure what its original intent was.

**Comment by FISHMANPET** [comment]
closing as duplicate of #39
