### ISSUE TITLE
Get-GOAuthTokenService - bad request

### ISSUE THREAD

**Issue by laheller** [umn-microsoft-automation/UMN-Google#46]
Hi @jbolduan @FISHMANPET @kylecweeks @travis-sobeck @tjsobeck 

For the existing **Service Account** (with full access to all resources) in Google Dev Console when I try to call function **Get-GOAuthTokenService** like:

> $GetTokenSplat = @{
   certPath = 'C:\Users\hellerl1\Downloads\CUE-Dashboard-362d2ea12bad.p12'
   certPswd = 'notasecret'
   iss      = 'hellerl1@cue-dashboard.iam.gserviceaccount.com'
   scope    = 'https://www.googleapis.com/auth/spreadsheets'
}

> $Token = Get-GOAuthTokenService @GetTokenSplat -Verbose

...it returns with following error:

> VERBOSE: POST https://www.googleapis.com/oauth2/v4/token with -1-byte payload
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.

Version of module UMN-Google is 1.2.9

Any idea, what's wrong?

**Comment by kylecweeks** [comment]
Your code is fine, but I think you have an issue with your service account. You'll get a 400 bad request if the service account or scope doesn't exist.

The scope you specify is correct for the spreadsheets API.

The cmdlet will fail with with errors specific to the certPath or password if invalid. 'System cannot find the file specified' or 'The specified network password is not correct.'

I would double check that the service account in your project is spelled correctly, enabled in IAM, and shows up under the APIs & services as a service account key (the .p12 file you generated).

**Comment by FISHMANPET** [comment]
You can use this function either by running it directly in VSCode/ISE, or by getting our module UMN-Common.  Pass it the relevant error (probably `$error[0]` if you're running this straight from the command line) and it will pull the actual error response out the error, since by default on Windows PowerShell eats it and just returns the generic error description for the error code.
```powershell
function Get-WebReqErrorDetails {
	<#
		.SYNOPSIS
			Returns JSON Responsbody data from an Error thrown by Invoke-Webrequest or Invoke-RestMethod
		.DESCRIPTION
			Returns JSON Responsbody data from an Error thrown by Invoke-Webrequest or Invoke-RestMethod
		.PARAMETER err
			Error thrown by Invoke-Webrequest or Invoke-RestMethod
		.NOTES
			Author: Travis Sobeck
	#>
	[CmdletBinding()]
	param
	(
		[Parameter(Mandatory)]
		[System.Management.Automation.ErrorRecord]$err
	)
	
	$reader = New-Object System.IO.StreamReader($err.Exception.Response.GetResponseStream())
	$reader.BaseStream.Position = 0
	$reader.DiscardBufferedData()
	return ($reader.ReadToEnd() | ConvertFrom-Json)
}
```

**Comment by laheller** [comment]
> You can use this function either by running it directly in VSCode/ISE, or by getting our module UMN-Common. Pass it the relevant error (probably `$error[0]` if you're running this straight from the command line) and it will pull the actual error response out the error, since by default on Windows PowerShell eats it and just returns the generic error description for the error code.
> 
> ```powershell
> function Get-WebReqErrorDetails {
> 	<#
> 		.SYNOPSIS
> 			Returns JSON Responsbody data from an Error thrown by Invoke-Webrequest or Invoke-RestMethod
> 		.DESCRIPTION
> 			Returns JSON Responsbody data from an Error thrown by Invoke-Webrequest or Invoke-RestMethod
> 		.PARAMETER err
> 			Error thrown by Invoke-Webrequest or Invoke-RestMethod
> 		.NOTES
> 			Author: Travis Sobeck
> 	#>
> 	[CmdletBinding()]
> 	param
> 	(
> 		[Parameter(Mandatory)]
> 		[System.Management.Automation.ErrorRecord]$err
> 	)
> 	
> 	$reader = New-Object System.IO.StreamReader($err.Exception.Response.GetResponseStream())
> 	$reader.BaseStream.Position = 0
> 	$reader.DiscardBufferedData()
> 	return ($reader.ReadToEnd() | ConvertFrom-Json)
> }
> ```

Tried that function and it returned following:

> error             : invalid_grant
> error_description : Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
> 

What the hell that error means?

**Comment by laheller** [comment]
@kylecweeks  @FISHMANPET 

OK, problem solved. Tried to run **Get-GOAuthTokenService** from my local computer connected via VPN to company network. Then the above error comes.
As soon as I executed the command on one of company VM (via remote desktop), no more errors.

Issue can be closed.
